### ISSUE TITLE
Finder location

### ISSUE THREAD

**Issue by leynier** [daxslab/cuba-weather#35]

**Comment by luiscib3r** [comment]
https://github.com/correaleyval/cuba-weather/blob/master/cuba_weather/finder.py

**Comment by leynier** [comment]
https://github.com/leynier/cuba-weather/blob/finder-location/cuba_weather/finder.py

@correaleyval I implement an improvement to your idea using the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) (using the [python-Levenshtein](https://pypi.org/project/python-Levenshtein/) module).

If the given location is not contained in any of the known locations, the location with the least distance of Levenshtein is returned.

I already added the dependency to `setup.py` and created a `requirements.txt` file.

@glpzzz this is the pull request: https://github.com/daxslab/cuba-weather/pull/36
